### ISSUE TITLE
Tautulli SSO

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#244]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The possibility to integrate Tautulli with passbook would be great, whether this is just a matter of documenting it or adding support in passbook.

**Describe alternatives you've considered**
Logging in manually with a local account like a pleb 👀 

**Additional context**
N/A.

**Comment by BeryJu** [comment]
Tautulli seems to support HTTP Basic auth. Sending a custom HTTP Basic Auth header based on passbook attributes was on the todo list already.

**Comment by BeryJu** [comment]
With latest master this is now implemented, only missing docs
