### ISSUE TITLE
OAuth2 provider redirect URI is case sensitive

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#249]
**Describe the bug**
OAuth2 provider redirect URI is case sensitive.

**To Reproduce**
1. Attempt login to OAuth2 application. Success is assumed
2. Capitalise any part of the redirect URI in the OAuth2 provider configuration.
3. Retry login to the application.
4. See error.

**Expected behavior**
Would expect redirect URI to not be case-sensitive.

**Screenshots**
N/A.

**Logs**
N/A.

**Version and Deployment (please complete the following information):**
 - passbook version: 0.10.5
 - Deployment: docker-compose

**Additional context**
N/A.

**Comment by BeryJu** [comment]
This also affects the Destination check for the SAML2 Provider.
