### ISSUE TITLE
Backup/Restore Functionality

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#252]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It's be great if there were a backup/restore function in passbook. For instance a section of the web interface which can generate a ZIP of the configuration to be downloaded. Support for uploading backups for restore would also be useful.   
The sort of functionality I have in mind is already present in Sonarr/Radarr/Lidarr, so perhaps it could be modelled on that?

As a stretch, scheduled backups would also be great, à la Sonarr/Radarr/Lidarr.

**Describe alternatives you've considered**
Backing up the volume like a pleb.

**Additional context**
N/A.

**Comment by badsmoke** [comment]
I read that the backup function no longer exists, which is a pity.

a simple dump download and upload, will make this all very relaxed

**Comment by BeryJu** [comment]
You can use the blueprint export feature to export all objects to YAML to define your authentik setup as code: https://goauthentik.io/developer-docs/blueprints/export

For full backups it is recommended to use PostgreSQL native tools as the inbuilt backup was never very reliable and often broke (hence it was removed)
