### ISSUE TITLE
Search fields for users, groups, and more

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#253]
**Is your feature request related to a problem? Please describe.**
With no way to search, it can take longer than necessary to find users, groups, property mappings, and anything else with multi-page lists.

**Describe the solution you'd like**
A search field for users, groups, property mappings, flows, stages, and any other list which is likely to exceed a single page.

**Describe alternatives you've considered**
Paging through the list and searching with my eyes like a pleb.

**Additional context**
N/A.

**Comment by BeryJu** [comment]
Is implemented in master, will be in 0.11
