### ISSUE TITLE
Proxy provider HTTP-Basic Password not obfuscated

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#265]
**Describe the bug**
In the edit page of a proxy provider, the HTTP-Basic password is shown in plaintext.

**To Reproduce**
1. Create proxy provider with any set of credentials.
2. Save.
3. Edit the provider.
4. See plaintext password.

**Expected behavior**
This should be obfuscated.

**Screenshots**
N/A.

**Logs**
N/A.

**Version and Deployment (please complete the following information):**
 - passbook version: 0.10.9-stable
 - Deployment: docker-compose

**Additional context**
N/A.

**Comment by BeryJu** [comment]
I assume you mean the `HTTP-Basic Password` field? This field doesn't hold the actual password, it saves which user or group attribute should be used for the password.

The help_text doesn't describe that 100% clearly, I'll update it.
