### ISSUE TITLE
Overview cards link to the relevant views

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#270]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great if the cards in the overview (e.g. policies, users, etc.) would navigate to the relevant view (i.e. policies -> `/administration/policies/`) when clicked.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by BeryJu** [comment]
This is actually a feature that has been removed, since the Policies card shows a Modal on click to clear the cache. I'll see if I can re-implement this in a consistent way so its clear what the click does
