### ISSUE TITLE
Icon upload for applications

### ISSUE THREAD

**Issue by tigattack** [BeryJu/passbook#320]
**Is your feature request related to a problem? Please describe.**
Yes, but it isn't passbook's fault.
The icon URL for my vCenter application in passbook points to the favicon of my vCenter, which means the icon doesn't load if the browser doesn't trust vCenter's certificate.

My suggestion would fix this and similar issues, such as icon URLs pointing at external locations not working when the client has local network access but no internet access.

**Describe the solution you'd like**
I'd like to be able to upload an icon for applications.
I don't want to be able to upload an icon _and_ provide an icon URL,  I just want to have the ability to choose between the two.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by BeryJu** [comment]
As part of the 0.13 release, a lot of the Admin UI will be redone to rely less on non-coherent lists of Objects and more to show relevent Information of Objects and allow common actions.

This will also include a few wizards, one of which will be for Application creation. This will include a selection of templates, for applications which have documented integrations. These applications will also have bundeled icons. For custom applications, I'm not 100% sure how to implement it the cleanest way.

**Comment by tigattack** [comment]
Awesome, cheers mate.

Regarding upload for custom applications, perhaps a small "gallery management" sort of thing could be useful, with the option to upload icons or select an existing one. The option to delete would be good, too. Similar to the WordPress media management pop-up I guess.

**Comment by BeryJu** [comment]
Ye for the UI its probably gonna be a File-Select type field on the Application Edit page. I'm just thinking about the backend implementation, as I dont want to have to add persistency to the main container, but also storing binary blobs in the Database is not the best idea.
